const message = {
  success: {
    getSearch: "Search data fetched successfully",
    getList: "List data fetched successfully",
    getCreate: "Create data fetched successfully",
    create: "Created successfully",
    getEdit: "Edit data fetched successfully",
    edit: "Updated successfully",
    delete: "Deleted successfully",
  },
  error: {
    create: "Failed to create",
    update: "Failed to update",
    delete: "Failed to delete",
  },
  validation: {
    required: "This field is required",
    unique: "This field must be unique",
  },
  notFound: "Not found",
  unauthorized: "Unauthorized",
  forbidden: "Forbidden",
  internalServerError: "Internal server error",
  badRequest: "Bad request",
  notImplemented: "Not implemented",
  serviceUnavailable: "Service unavailable",
  gatewayTimeout: "Gateway timeout",
  networkAuthenticationRequired: "Network authentication required",
  paymentRequired: "Payment required",
  conflict: "Conflict",
  tooManyRequests: "Too many requests",
  requestHeaderFieldsTooLarge: "Request header fields too large",
  tooEarly: "Too early",
  upgradeRequired: "Upgrade required",
  preconditionFailed: "Precondition failed",
  payloadTooLarge: "Payload too large",
  uriTooLong: "URI too long",
  unsupportedMediaType: "Unsupported media type",
  rangeNotSatisfiable: "Range not satisfiable",
  expectationFailed: "Expectation failed",
  imATeapot: "I'm a teapot",
  misdirectedRequest: "Misdirected request",
  unprocessableEntity: "Unprocessable entity",
  locked: "Locked",
  failedDependency: "Failed dependency",
  httpVersionNotSupported: "HTTP version not supported",
  variantAlsoNegotiates: "Variant also negotiates",
  insufficientStorage: "Insufficient storage",
  loopDetected: "Loop detected",
  notExtended: "Not extended",
};

export default message;
